import {
  User,
  ClinicSettings,
  Appointment,
  Patient,
  Conversation,
  DashboardStats,
} from '../types';

export const initialCurrentUser: User = {
  id: 'usr_1',
  name: 'Dra. Camila Santos',
  email: 'camila@clinicalumina.com.br',
  role: 'admin',
  clinicId: 'clinic_1',
  avatar: 'https://images.unsplash.com/photo-1594824813591-10c0e5a88133?w=150&auto=format&fit=crop&q=80',
};

export const initialClinicSettings: ClinicSettings = {
  id: 'clinic_1',
  name: 'Clínica Lumina Estética & Odonto',
  niche: 'odontologia',
  phone: '+55 11 98765-4321',
  email: 'contato@clinicalumina.com.br',
  address: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
  botTone: 'formal',
  language: 'pt-BR',
  whatsapp: {
    status: 'connected',
    phoneNumber: '+55 11 98765-4321',
    deviceName: 'WhatsApp Business (iPhone 15)',
    lastSync: new Date().toISOString(),
  },
  workingHours: [
    { dayOfWeek: 1, dayName: 'Segunda-feira', isOpen: true, openTime: '08:00', closeTime: '19:00', breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 2, dayName: 'Terça-feira', isOpen: true, openTime: '08:00', closeTime: '19:00', breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 3, dayName: 'Quarta-feira', isOpen: true, openTime: '08:00', closeTime: '19:00', breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 4, dayName: 'Quinta-feira', isOpen: true, openTime: '08:00', closeTime: '19:00', breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 5, dayName: 'Sexta-feira', isOpen: true, openTime: '08:00', closeTime: '18:00', breakStart: '12:00', breakEnd: '13:00' },
    { dayOfWeek: 6, dayName: 'Sábado', isOpen: true, openTime: '08:00', closeTime: '14:00' },
    { dayOfWeek: 0, dayName: 'Domingo', isOpen: false, openTime: '08:00', closeTime: '12:00' },
  ],
  services: [
    { id: 'srv_1', name: 'Limpeza e Profilaxia', durationMinutes: 45, price: 180, category: 'Odontologia', active: true },
    { id: 'srv_2', name: 'Clareamento Dental a Laser', durationMinutes: 60, price: 850, category: 'Odontologia', active: true },
    { id: 'srv_3', name: 'Avaliação de Facetas de Resina', durationMinutes: 45, price: 150, category: 'Odontologia', active: true },
    { id: 'srv_4', name: 'Aplicação de Toxina Botulínica (Botox)', durationMinutes: 45, price: 1200, category: 'Estética', active: true },
    { id: 'srv_5', name: 'Preenchimento Labial com Ácido Hialurônico', durationMinutes: 60, price: 1400, category: 'Estética', active: true },
    { id: 'srv_6', name: 'Bioestimulador de Colágeno', durationMinutes: 60, price: 2100, category: 'Estética', active: true },
  ],
  professionals: [
    { id: 'prof_1', name: 'Dra. Camila Santos', role: 'Harmonização Facial & Estética', color: '#0d9488', active: true },
    { id: 'prof_2', name: 'Dr. Lucas Mendes', role: 'Ortodontia & Estética Dental', color: '#0284c7', active: true },
    { id: 'prof_3', name: 'Dr. Marcelo Ramos', role: 'Implantodontia & Cirurgia', color: '#7c3aed', active: true },
  ],
  nicheSpecificAnswers: {
    insuranceAccepted: 'Particular e reembolso',
    requiresDownpayment: 'Não, pagamento no local',
    parkingAvailable: 'Sim, gratuito no local',
  },
};

export const initialPatients: Patient[] = [
  {
    id: 'pat_1',
    name: 'Juliana Ferreira',
    phone: '+55 11 97123-4567',
    email: 'juliana.ferreira@gmail.com',
    document: '321.456.789-00',
    createdAt: '2026-01-15',
    totalAppointments: 4,
    noShowCount: 0,
    lastVisit: '2026-09-18',
    notes: 'Interesse em clareamento e manutenção de Botox anual.',
  },
  {
    id: 'pat_2',
    name: 'Mariana Silva Ribeiro',
    phone: '+55 11 98234-5678',
    email: 'mariana.silva@outlook.com',
    document: '456.789.123-11',
    createdAt: '2026-02-10',
    totalAppointments: 2,
    noShowCount: 0,
    lastVisit: '2026-08-25',
    notes: 'Paciente muito pontual, prefere horários no período da manhã.',
  },
  {
    id: 'pat_3',
    name: 'Carlos Eduardo Nogueira',
    phone: '+55 11 99345-6789',
    email: 'carlos.edu@empresa.com.br',
    document: '123.789.456-22',
    createdAt: '2026-03-01',
    totalAppointments: 5,
    noShowCount: 1,
    lastVisit: '2026-09-02',
    notes: 'Costuma reagendar viagens de última hora.',
  },
  {
    id: 'pat_4',
    name: 'Fernanda Albuquerque',
    phone: '+55 11 96456-7890',
    email: 'fe.albuquerque@gmail.com',
    document: '987.654.321-33',
    createdAt: '2026-04-12',
    totalAppointments: 3,
    noShowCount: 0,
    lastVisit: '2026-09-14',
    notes: 'Tratamento de bioestimulador de colágeno em andamento.',
  },
  {
    id: 'pat_5',
    name: 'Rafael Guimarães',
    phone: '+55 11 95567-8901',
    email: 'rafael.gui@yahoo.com.br',
    document: '654.321.987-44',
    createdAt: '2026-05-20',
    totalAppointments: 1,
    noShowCount: 1,
    lastVisit: '2026-07-10',
    notes: 'Faltou na última consulta sem avisar antes.',
  },
  {
    id: 'pat_6',
    name: 'Beatriz Vasconcelos',
    phone: '+55 11 94678-9012',
    email: 'bia.vasconcelos@hotmail.com',
    document: '789.123.456-55',
    createdAt: '2026-06-05',
    totalAppointments: 6,
    noShowCount: 0,
    lastVisit: '2026-09-22',
    notes: 'Paciente VIP, sempre indica amigas para a harmonização.',
  },
];

// Helper to get formatted date string for relative days
const getRelativeDateStr = (offsetDays: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const initialAppointments: Appointment[] = [
  {
    id: 'apt_1',
    patientId: 'pat_1',
    patientName: 'Juliana Ferreira',
    patientPhone: '+55 11 97123-4567',
    serviceId: 'srv_4',
    serviceName: 'Aplicação de Toxina Botulínica (Botox)',
    professionalId: 'prof_1',
    professionalName: 'Dra. Camila Santos',
    date: getRelativeDateStr(0), // Today
    time: '14:30',
    durationMinutes: 45,
    status: 'confirmed',
    price: 1200,
    notes: 'Retorno de 6 meses para testa e glabela.',
  },
  {
    id: 'apt_2',
    patientId: 'pat_2',
    patientName: 'Mariana Silva Ribeiro',
    patientPhone: '+55 11 98234-5678',
    serviceId: 'srv_2',
    serviceName: 'Clareamento Dental a Laser',
    professionalId: 'prof_2',
    professionalName: 'Dr. Lucas Mendes',
    date: getRelativeDateStr(0), // Today
    time: '16:00',
    durationMinutes: 60,
    status: 'scheduled',
    price: 850,
    notes: 'Segunda sessão de clareamento.',
  },
  {
    id: 'apt_3',
    patientId: 'pat_3',
    patientName: 'Carlos Eduardo Nogueira',
    patientPhone: '+55 11 99345-6789',
    serviceId: 'srv_1',
    serviceName: 'Limpeza e Profilaxia',
    professionalId: 'prof_2',
    professionalName: 'Dr. Lucas Mendes',
    date: getRelativeDateStr(0), // Today
    time: '10:00',
    durationMinutes: 45,
    status: 'confirmed',
    price: 180,
  },
  {
    id: 'apt_4',
    patientId: 'pat_4',
    patientName: 'Fernanda Albuquerque',
    patientPhone: '+55 11 96456-7890',
    serviceId: 'srv_5',
    serviceName: 'Preenchimento Labial',
    professionalId: 'prof_1',
    professionalName: 'Dra. Camila Santos',
    date: getRelativeDateStr(1), // Tomorrow
    time: '11:00',
    durationMinutes: 60,
    status: 'confirmed',
    price: 1400,
    notes: 'Lembrete automático confirmado via WhatsApp.',
  },
  {
    id: 'apt_5',
    patientId: 'pat_5',
    patientName: 'Rafael Guimarães',
    patientPhone: '+55 11 95567-8901',
    serviceId: 'srv_3',
    serviceName: 'Avaliação de Facetas de Resina',
    professionalId: 'prof_3',
    professionalName: 'Dr. Marcelo Ramos',
    date: getRelativeDateStr(-2), // 2 days ago
    time: '15:00',
    durationMinutes: 45,
    status: 'no_show',
    price: 150,
    notes: 'Não compareceu e não respondeu à confirmação.',
  },
  {
    id: 'apt_6',
    patientId: 'pat_6',
    patientName: 'Beatriz Vasconcelos',
    patientPhone: '+55 11 94678-9012',
    serviceId: 'srv_6',
    serviceName: 'Bioestimulador de Colágeno',
    professionalId: 'prof_1',
    professionalName: 'Dra. Camila Santos',
    date: getRelativeDateStr(2),
    time: '09:30',
    durationMinutes: 60,
    status: 'scheduled',
    price: 2100,
  },
  {
    id: 'apt_7',
    patientId: 'pat_1',
    patientName: 'Juliana Ferreira',
    patientPhone: '+55 11 97123-4567',
    serviceId: 'srv_1',
    serviceName: 'Limpeza e Profilaxia',
    professionalId: 'prof_2',
    professionalName: 'Dr. Lucas Mendes',
    date: getRelativeDateStr(-1),
    time: '14:00',
    durationMinutes: 45,
    status: 'confirmed',
    price: 180,
  },
  {
    id: 'apt_8',
    patientId: 'pat_3',
    patientName: 'Carlos Eduardo Nogueira',
    patientPhone: '+55 11 99345-6789',
    serviceId: 'srv_2',
    serviceName: 'Clareamento Dental',
    professionalId: 'prof_2',
    professionalName: 'Dr. Lucas Mendes',
    date: getRelativeDateStr(-4),
    time: '11:00',
    durationMinutes: 60,
    status: 'cancelled',
    price: 850,
    notes: 'Cancelado pelo paciente 24h antes pelo WhatsApp.',
  },
];

export const initialConversations: Conversation[] = [
  {
    id: 'conv_1',
    patientId: 'pat_1',
    patientName: 'Juliana Ferreira',
    patientPhone: '+55 11 97123-4567',
    channel: 'whatsapp',
    attendant: 'ai',
    unreadCount: 0,
    lastMessage: 'Perfeito! Sua consulta está confirmada para hoje às 14:30 com a Dra. Camila.',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    messages: [
      {
        id: 'm1',
        conversationId: 'conv_1',
        sender: 'patient',
        text: 'Olá, bom dia! Gostaria de confirmar se meu horário com a Dra. Camila hoje está mantido?',
        timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        status: 'read',
      },
      {
        id: 'm2',
        conversationId: 'conv_1',
        sender: 'ai',
        text: 'Olá, Juliana! Sim, seu procedimento de Aplicação de Botox está confirmado para hoje às 14:30 com a Dra. Camila Santos. 😊',
        timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
        status: 'read',
      },
      {
        id: 'm3',
        conversationId: 'conv_1',
        sender: 'patient',
        text: 'Ótimo! Tem estacionamento no local?',
        timestamp: new Date(Date.now() - 1000 * 60 * 13).toISOString(),
        status: 'read',
      },
      {
        id: 'm4',
        conversationId: 'conv_1',
        sender: 'ai',
        text: 'Sim! Temos convênio com estacionamento gratuito com manobrista bem na entrada do prédio. Até breve!',
        timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        status: 'read',
      },
    ],
  },
  {
    id: 'conv_2',
    patientId: 'pat_2',
    patientName: 'Mariana Silva Ribeiro',
    patientPhone: '+55 11 98234-5678',
    channel: 'whatsapp',
    attendant: 'human',
    unreadCount: 2,
    lastMessage: 'Vou precisar atrasar uns 15 minutinhos por causa do trânsito na Marginal, tudo bem?',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    messages: [
      {
        id: 'm201',
        conversationId: 'conv_2',
        sender: 'ai',
        text: 'Olá Mariana! Passando para lembrar da sua sessão de Clareamento hoje às 16:00 com o Dr. Lucas.',
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        status: 'read',
      },
      {
        id: 'm202',
        conversationId: 'conv_2',
        sender: 'patient',
        text: 'Oi! Vou precisar atrasar uns 15 minutinhos por causa do trânsito na Marginal, tudo bem?',
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        status: 'delivered',
      },
      {
        id: 'm203',
        conversationId: 'conv_2',
        sender: 'system',
        text: 'Atendimento assumido pela recepção humana.',
        timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
      },
    ],
  },
  {
    id: 'conv_3',
    patientId: 'pat_4',
    patientName: 'Fernanda Albuquerque',
    patientPhone: '+55 11 96456-7890',
    channel: 'whatsapp',
    attendant: 'ai',
    unreadCount: 0,
    lastMessage: 'Obrigada! Já anotei aqui na minha agenda.',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    messages: [
      {
        id: 'm301',
        conversationId: 'conv_3',
        sender: 'ai',
        text: 'Olá Fernanda! Confirmamos seu horário de Preenchimento Labial amanhã às 11:00 com a Dra. Camila. Lembramos de evitar anti-inflamatórios hoje.',
        timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
        status: 'read',
      },
      {
        id: 'm302',
        conversationId: 'conv_3',
        sender: 'patient',
        text: 'Obrigada! Já anotei aqui na minha agenda.',
        timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
        status: 'read',
      },
    ],
  },
  {
    id: 'conv_4',
    patientId: 'pat_5',
    patientName: 'Rafael Guimarães',
    patientPhone: '+55 11 95567-8901',
    channel: 'whatsapp',
    attendant: 'human',
    unreadCount: 0,
    lastMessage: 'Gostaria de remarcar aquela consulta da semana passada que acabei perdendo.',
    lastMessageTimestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    messages: [
      {
        id: 'm401',
        conversationId: 'conv_4',
        sender: 'patient',
        text: 'Gostaria de remarcar aquela consulta da semana passada que acabei perdendo.',
        timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
        status: 'read',
      },
    ],
  },
];

export const initialDashboardStats: DashboardStats = {
  conversationsToday: 38,
  scheduledToday: 8,
  confirmedToday: 6,
  noShowsThisWeek: 1,
  noShowReductionRate: 78,
  weeklyNoShows: [
    { weekLabel: 'Semana 1', scheduled: 42, noShows: 9, confirmed: 33, rate: 21 },
    { weekLabel: 'Semana 2', scheduled: 48, noShows: 6, confirmed: 42, rate: 12 },
    { weekLabel: 'Semana 3', scheduled: 54, noShows: 4, confirmed: 50, rate: 7 },
    { weekLabel: 'Semana 4 (Atual)', scheduled: 51, noShows: 1, confirmed: 50, rate: 2 },
  ],
};
